# Generated by Django 3.0.1 on 2020-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_oz', models.IntegerField()),
                ('lb', models.IntegerField()),
                ('oz', models.IntegerField()),
                ('ton', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('g', models.IntegerField()),
            ],
        ),
    ]
