# Generated by Django 3.0.1 on 2020-03-27 05:40

from django.db import migrations

def populate_db(apps, schema_editor):
    """
    This is a new function that I define myself.  It takes two parameters.

    The first parameter `apps` is an application registry which enables access
    to my models without needing to use the import statement.  The details are
    a bit involved, but the application registry lets me access previous
    versions of my models; importing the classes via the import statement would
    only let me use those classes as they exist right now.

    The second parameter `schema_editor` may be used when I change the layout
    of fields in a model.  Since we are only interested in creating new
    records right now, we can ignore it.
    """

    Factor = apps.get_model('unitconv', 'Factor')
    f = Factor(t_oz = 1.0, lb = 14.5833, oz = 0.911458, ton = 29166.7, kg = 32.1507, g = 0.0321507)
    f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
